# Generated by Django 6.0.8 on 2026-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='color_mapa',
            field=models.CharField(default='#20c997', help_text='Color utilizado para representar la zona en el mapa. Ejemplo: #20c997', max_length=7),
        ),
        migrations.AddField(
            model_name='zona',
            name='geometria',
            field=models.JSONField(blank=True, help_text='Calles o sectores que pertenecen a la zona, guardados en formato GeoJSON.', null=True),
        ),
    ]
