# Generated by Django 6.0.8 on 2026-08-07 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.CharField(db_index=True, max_length=15)),
                ('motivo', models.CharField(choices=[('SIN_ESTACIONAMIENTO', 'Sin estacionamiento activo'), ('ZONA_INCORRECTA', 'Estacionamiento en zona incorrecta'), ('OTRO', 'Otro')], default='SIN_ESTACIONAMIENTO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infracciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones', to='vehiculos.vehiculo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infracciones', to='zonas.zona')),
            ],
            options={
                'verbose_name': 'infracción',
                'verbose_name_plural': 'infracciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
