# Generated by Django 6.0.8 on 2026-08-05 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.CharField(help_text='Ejemplo: ABCD123', max_length=10, unique=True, verbose_name='Número de chapa')),
                ('tipo', models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('MOTOCICLETA', 'Motocicleta'), ('OTRO', 'Otro')], default='AUTOMOVIL', max_length=20, verbose_name='Tipo de vehículo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['chapa'],
            },
        ),
    ]
