# Generated by Django 6.0.8 on 2026-08-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ACTIVO', max_length=15)),
                ('tiempo_utilizado', models.PositiveIntegerField(blank=True, null=True)),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacionamientos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacionamientos', to='vehiculos.vehiculo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacionamientos', to='zonas.zona')),
            ],
            options={
                'verbose_name': 'estacionamiento',
                'verbose_name_plural': 'estacionamientos',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('vehiculo',), name='vehiculo_con_un_solo_estacionamiento_activo')],
            },
        ),
    ]
